"""
build_installer.py — Build script for creating the Windows distributable.

Steps:
1. Build .exe with PyInstaller
2. Generate Inno Setup script (.iss) for Windows installer

Usage:
    python build_installer.py
"""

import os
import sys
import subprocess
import shutil

APP_NAME = "MRAC Simulink"
APP_VERSION = "1.1.0"
APP_PUBLISHER = "Herian Perdana"
APP_EXE = "MRAC_Simulink.exe"
APP_ID = "{{B7E8F3A2-4D6C-4F8A-9B2E-1A3C5D7E9F0B}"

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DIST_DIR = os.path.join(BASE_DIR, "dist", "MRAC_Simulink")
ICON_PATH = os.path.join(BASE_DIR, "mrac_icon.ico")
OUTPUT_DIR = os.path.join(BASE_DIR, "installer_output")


def step1_build_exe():
    """Build the standalone EXE with PyInstaller."""
    print("\n" + "=" * 60)
    print("  STEP 1: Building EXE with PyInstaller")
    print("=" * 60)

    # Clean previous builds
    for d in ['build', 'dist']:
        p = os.path.join(BASE_DIR, d)
        if os.path.exists(p):
            print(f"  Cleaning {d}/...")
            shutil.rmtree(p)

    cmd = [
        sys.executable, '-m', 'PyInstaller',
        'build.spec',
        '--clean',
        '--noconfirm',
    ]

    print(f"  Running: {' '.join(cmd)}")
    result = subprocess.run(cmd, cwd=BASE_DIR)

    if result.returncode != 0:
        print("  ERROR: PyInstaller build failed!")
        sys.exit(1)

    print(f"  EXE built at: {DIST_DIR}")

    # Check EXE exists
    exe_path = os.path.join(DIST_DIR, APP_EXE)
    if os.path.exists(exe_path):
        size_mb = os.path.getsize(exe_path) / (1024 * 1024)
        print(f"  EXE size: {size_mb:.1f} MB")
    else:
        print("  WARNING: EXE not found at expected path")


def step2_generate_iss():
    """Generate an Inno Setup script for creating the Windows installer."""
    print("\n" + "=" * 60)
    print("  STEP 2: Generating Inno Setup Script")
    print("=" * 60)

    os.makedirs(OUTPUT_DIR, exist_ok=True)

    iss_content = f"""; Inno Setup Script for {APP_NAME}
; Generated by build_installer.py

#define MyAppName "{APP_NAME}"
#define MyAppVersion "{APP_VERSION}"
#define MyAppPublisher "{APP_PUBLISHER}"
#define MyAppExeName "{APP_EXE}"

[Setup]
AppId={APP_ID}
AppName={{#MyAppName}}
AppVersion={{#MyAppVersion}}
AppPublisher={{#MyAppPublisher}}
DefaultDirName={{autopf}}\\{{#MyAppName}}
DefaultGroupName={{#MyAppName}}
AllowNoIcons=yes
OutputDir={OUTPUT_DIR.replace(os.sep, '\\\\')}
OutputBaseFilename=MRAC_Simulink_Setup_v{APP_VERSION}
SetupIconFile={ICON_PATH.replace(os.sep, '\\\\')}
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=lowest
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop shortcut"; GroupDescription: "Additional shortcuts:"
Name: "startmenuicon"; Description: "Create a &Start Menu shortcut"; GroupDescription: "Additional shortcuts:"; Flags: checkedonce

[Files]
Source: "{DIST_DIR.replace(os.sep, '\\\\')}\\*"; DestDir: "{{app}}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{{group}}\\{{#MyAppName}}"; Filename: "{{app}}\\{{#MyAppExeName}}"
Name: "{{group}}\\Uninstall {{#MyAppName}}"; Filename: "{{uninstallexe}}"
Name: "{{autodesktop}}\\{{#MyAppName}}"; Filename: "{{app}}\\{{#MyAppExeName}}"; Tasks: desktopicon

[Run]
Filename: "{{app}}\\{{#MyAppExeName}}"; Description: "Launch {APP_NAME}"; Flags: nowait postinstall skipifsilent
"""

    iss_path = os.path.join(BASE_DIR, "installer.iss")
    with open(iss_path, 'w', encoding='utf-8') as f:
        f.write(iss_content)

    print(f"  Inno Setup script: {iss_path}")
    print()
    print("  To create the installer (.exe setup wizard):")
    print("  1. Install Inno Setup from: https://jrsoftware.org/isdl.php")
    print(f"  2. Open '{iss_path}' in Inno Setup Compiler")
    print("  3. Click Build -> Compile")
    print(f"  4. Installer will be saved to: {OUTPUT_DIR}")


def step3_create_portable_zip():
    """Create a portable ZIP distribution (no installer needed)."""
    print("\n" + "=" * 60)
    print("  STEP 3: Creating Portable ZIP")
    print("=" * 60)

    if not os.path.exists(DIST_DIR):
        print("  SKIP: dist folder not found (build first)")
        return

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    zip_name = f"MRAC_Simulink_v{APP_VERSION}_Portable"
    zip_path = os.path.join(OUTPUT_DIR, zip_name)

    print(f"  Creating: {zip_path}.zip")
    shutil.make_archive(zip_path, 'zip', os.path.dirname(DIST_DIR), "MRAC_Simulink")

    final_zip = zip_path + ".zip"
    if os.path.exists(final_zip):
        size_mb = os.path.getsize(final_zip) / (1024 * 1024)
        print(f"  ZIP created: {final_zip} ({size_mb:.1f} MB)")
    else:
        print("  WARNING: ZIP creation may have failed")


def main():
    print("\n" + "=" * 60)
    print(f"  {APP_NAME} — BUILD INSTALLER")
    print(f"  Version: {APP_VERSION}")
    print("=" * 60)

    step1_build_exe()
    step2_generate_iss()
    step3_create_portable_zip()

    print("\n" + "=" * 60)
    print("  BUILD COMPLETE!")
    print("=" * 60)
    print(f"""
  Output files:
    dist/MRAC_Simulink/      — Standalone app folder
    installer.iss             — Inno Setup script (compile for .exe installer)
    installer_output/         — Contains portable ZIP

  Distribution options:
    1. PORTABLE: Share the ZIP file — users just extract and run
    2. INSTALLER: Compile installer.iss with Inno Setup for a setup wizard
""")


if __name__ == "__main__":
    main()
